//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildingBlocks.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BuildingBlocks.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Product Categories..
        /// </summary>
        public static string DuplicateProductCategories {
            get {
                return ResourceManager.GetString("DuplicateProductCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Category Description..
        /// </summary>
        public static string EmptyCategoryDescription {
            get {
                return ResourceManager.GetString("EmptyCategoryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Category NameEn..
        /// </summary>
        public static string EmptyCategoryNameEn {
            get {
                return ResourceManager.GetString("EmptyCategoryNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Product Description..
        /// </summary>
        public static string EmptyProductDescription {
            get {
                return ResourceManager.GetString("EmptyProductDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Product ImageUrl..
        /// </summary>
        public static string EmptyProductImageUrl {
            get {
                return ResourceManager.GetString("EmptyProductImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Product NameAr..
        /// </summary>
        public static string EmptyProductNameAr {
            get {
                return ResourceManager.GetString("EmptyProductNameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Product NameEn..
        /// </summary>
        public static string EmptyProductNameEn {
            get {
                return ResourceManager.GetString("EmptyProductNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Category Description Length..
        /// </summary>
        public static string InvalidCategoryDescriptionLength {
            get {
                return ResourceManager.GetString("InvalidCategoryDescriptionLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Category NameEn Length..
        /// </summary>
        public static string InvalidCategoryNameEnLength {
            get {
                return ResourceManager.GetString("InvalidCategoryNameEnLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Product Categories..
        /// </summary>
        public static string InvalidProductCategories {
            get {
                return ResourceManager.GetString("InvalidProductCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Product Description Length..
        /// </summary>
        public static string InvalidProductDescriptionLength {
            get {
                return ResourceManager.GetString("InvalidProductDescriptionLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Product ExpiryDate..
        /// </summary>
        public static string InvalidProductExpiryDate {
            get {
                return ResourceManager.GetString("InvalidProductExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Product Id..
        /// </summary>
        public static string InvalidProductId {
            get {
                return ResourceManager.GetString("InvalidProductId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Product ImageUrl Length..
        /// </summary>
        public static string InvalidProductImageUrlLength {
            get {
                return ResourceManager.GetString("InvalidProductImageUrlLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Product NameAr Length..
        /// </summary>
        public static string InvalidProductNameArLength {
            get {
                return ResourceManager.GetString("InvalidProductNameArLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Product NameEn Length..
        /// </summary>
        public static string InvalidProductNameEnLength {
            get {
                return ResourceManager.GetString("InvalidProductNameEnLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Product ProductionDate..
        /// </summary>
        public static string InvalidProductProductionDate {
            get {
                return ResourceManager.GetString("InvalidProductProductionDate", resourceCulture);
            }
        }
    }
}
